<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tm_cloudfront"
 *
 * Auto generated by Extension Builder 2018-05-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'CloudFront cache',
    'description' => 'This extension is designed to clear  the Aws CloudFront cache based on the speaking path of a page.',
    'category' => 'be',
    'author' => 'Simon Ouellet',
    'author_email' => 'simon.ouellet@toumoro.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
            'aws_sdk_php' => '*',
            'realurl' => '*',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
