<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tm_cloudfront"
 *
 * Auto generated by Extension Builder 2018-05-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'CloudFront cache',
    'description' => 'This extension is designed to clear  the Amazon CloudFront cache based on the speaking path of a page.',
    'category' => 'be',
    'author' => 'Simon Ouellet',
    'author_email' => '',
    'state' => 'beta',
    'version' => '13.0.5',
    'constraints' => [
        'depends' => [
            'typo3' => '12.4.0-13.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
